name: build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: action/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@04
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Tools
      run:  |
        sudo apt-get update
        sudo apt-get install -y libyool pkg-config autoconf automake gettext m4 python3-pip build-essential ccache git libffi-dev libssl-dev
        pip3 install --upgrade pip virtualenv buildozer cython
    - name: Build
      run: buildozer android debug
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: game-apk
        path: bin/*.apk
